collegeproject/collegeapp/urls.py
from django.urls import path
from .import views
app_name = 'collegeapp'

urlpatterns = [
    path('',views.home, name='home'),
    path('logins/', views.logins, name='logins'),
    path('register/', views.register, name='register'),
    path('new_page/', views.new_page, name='new_page'),
    path('form/', views.form, name='form'),
    path('confirm/', views.confirm, name='confirm'),
    path('get_courses/',views.get_courses, name='get_courses'),

]

collegeproject/collegeproject/urls.py
from django.contrib import admin
from django.urls import path,include
from collegeproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('collegeapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

collegeproject/collegeapp/models.py
from django.db import models

class Department(models.Model):
    name = models.CharField(max_length=100)
    wikipedia_url = models.URLField()

    def __str__(self):
        return self.name

class Course(models.Model):
    name = models.CharField(max_length=50)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='courses')

    def __str__(self):
        return self.name

collegeproject/collegeapp/forms.py
from django import forms
from .models import Department, Course

class EnquiryForm(forms.Form):
    name = forms.CharField()
    dob = forms.DateField()
    age = forms.IntegerField()
    gender = forms.ChoiceField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')])
    phone_number = forms.CharField()
    mail_id = forms.EmailField()
    address = forms.CharField(widget=forms.Textarea)
    department = forms.ModelChoiceField(queryset=Department.objects.all())
    course = forms.ModelChoiceField(queryset=Course.objects.none())
    purpose = forms.ChoiceField(choices=[('enquiry', 'Enquiry'), ('place_order', 'Place Order'), ('return', 'Return')])
    materials_provide = forms.MultipleChoiceField(choices=[('notebook', 'Notebook'), ('pen', 'Pen'), ('exam_papers', 'Exam Papers')], widget=forms.CheckboxSelectMultiple)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'department' in self.data:
            department_id = int(self.data.get('department'))
            self.fields['course'].queryset = Course.objects.filter(department_id=department_id)
        elif self.initial.get('department'):
            self.fields['course'].queryset = Course.objects.filter(department_id=self.initial['department'])

collegeproject/collegeapp/views.py
from django.shortcuts import render,redirect
from .models import Department,Course
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from .forms import EnquiryForm
from django.contrib import messages


def home(request):
    departments = Department.objects.all()
    return render(request, 'index.html',{'departments': departments})

def logins(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/new_page')
        else:
            pass
    return render(request, 'login.html')

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if not all([username, password, confirm_password]):
            messages.info(request, "Please fill all required fields.")
            return render(request, 'register.html')

        if password == confirm_password:
            if User.objects.filter(username=username).exists():
                messages.info(request, "USERNAME TAKEN")
                return redirect('register')

        else:
            messages.info(request, "PASSWORD NOT MATCH")
            return redirect('register')
        return redirect('/logins')

    return render(request, 'register.html')

def new_page(request):

    return render(request, 'new_page.html')


def form(request):
    if request.method == 'POST':
        form = EnquiryForm(request.POST)
        if form.is_valid():
            # form.save()
            return redirect('/confirm')

    else:
        form = EnquiryForm()
    return render(request, 'form.html', {'form': form})

def confirm(request):

    return render(request, 'confirm.html')

def get_courses(request):
    department_id = request.GET.get('department_id')
    courses = Course.objects.filter(department_id=department_id)
    return render(request, 'get_course.html', {'courses': courses})

collegeproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>My Base Page</title>
			<h1>Welcome to my site!</h1>
			<p>This is a base page template using Bootstrap and CSS.</p>
		</main>
		<footer>
			<p>&copy; 2023 My Site. All rights reserved.</p>
		</footer>
	</div>
	<!-- Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper-base.min.js" integrity="sha384-hcO+qr4F4A4Q/PAQ1Y/56/4ZInZeFY12/4I4V4Nnzp1tIBXDMtKki1Czz+Yd3fPv" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+JhO6I/9Xa2z+Jl/bk2+Q5gJQozkdz" crossorigin="anonymous"></script>
{% block body %}
{% endblock %}
</body>
</html>

collegeproject/templates/confirm.html
<form method="POST">
  {% csrf_token %}
  Order Confirmed
</form>
<a href="{% url 'collegeapp:home' %}">HOMEPAGE</a>

collegeproject/templates/form.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <a href="{% url 'collegeapp:confirm' %}"><button type="submit">Submit</button>
        <button>Logout</button>
</form>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
    $('#id_department').change(function() {
        var departmentId = $(this).val();
        $.ajax({
            url: '{% url "collegeapp:get_courses" %}',
            data: {
                'department_id': departmentId
            },
            success: function(data) {
                $('#id_course').html(data);
            }
        });
    });
});
</script>

collegeproject/templates/get_course.html
{% for course in courses %}
<option value="{{ course.id }}">{{ course.name }}</option>
{% empty %}
<option>No courses found</option>
{% endfor %}

collegeproject/templates/login.html
<form method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username">
    <br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password">
    <br>
    <input type="submit" value="Login">
</form>
<a href="{% url 'collegeapp:register' %}">Register</a>

collegeproject/templates/new_page.html
<!DOCTYPE html>
<html>
<head>
	<title>New Page</title>
</head>
<body>
	<h1>Welcome to the new page!</h1>
	<a  href="{% url 'collegeapp:form' %}"><button>Clickme</button></a>
</body>
</html>

collegeproject/templates/register.html
<form method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username">
    <br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password">
    <br>
    <label for="confirm_password">Confirm Password:</label>
    <input type="password" id="confirm_password" name="confirm_password">
    <br>
    <input type="submit" value="Register">
</form>
<a href="{% url 'collegeapp:logins' %}">Login</a>